### ISSUE TITLE
Docs: Unable to install for Windows or macOS

### ISSUE THREAD

**Issue by michaeldavie** [aws-deadline/deadline-cloud-for-blender#104]
### Documentation Issue

I can't get the submitter working in either Windows or macOS. More detailed installation guidance would be greatly appreciated.

**Comment by michaeldavie** [comment]
I resolved the installation on macOS using this script within Blender: https://github.com/luckychris/install_blender_python_modules

**Comment by andymanaws** [comment]
This looks like something is missing from the docs - good call.
This should enable it to work


1. Add script directory path to Blender
    1. In Blender,  select "Edit" > "Preferences" > "File Paths" > "Script Directories"
    2. Add new script directory (name only helps identify)
        1. Windows: %USERPROFILE%\DeadlineCloudSubmitter\Submitters\Blender\python
        2. Linux: ~/DeadlineCloudSubmitter/Submitters/Blender/python


2. Restart Blender (script directory changes only take affect on restart)
3. Enable the Add-on 
    1. Select "Edit" > "Preferences" > "Add-ons" tab.
    2. Search “Deadline”
    3. Click the checkbox beside the add-on to enable
4. Verify successful installation:
    1. Select “Render” > “Deadline Cloud Dialog”
    2. The submitter dialog should pop up

**Comment by michaeldavie** [comment]
That helps, thanks. Please add this info to the installation documentation as well: https://docs.aws.amazon.com/deadline-cloud/latest/userguide/submitter.html

**Comment by lucaseck** [comment]
The two PRs above should help clarify the installation instructions. The public documentation has been [updated](https://docs.aws.amazon.com/deadline-cloud/latest/userguide/submitter.html#load-dca-plugin) as well with the installation instructions. Hopefully that helps anyone else who may be unsure of what's needed to install the add-on.

I'm going to close this now as completed. If there's anything else that is still unclear please feel free to cut another issue and thank you for pointing this out!
