### ISSUE TITLE
Bug: Directory auto-detected as file; submission fails

### ISSUE THREAD

**Issue by michaeldavie** [aws-deadline/deadline-cloud-for-blender#105]
### Expected Behaviour

Submission succeeds

### Current Behaviour

Job submission fails because the fluid simulation cache is listed as a file and can't be removed.
<img width="851" alt="image" src="https://github.com/aws-deadline/deadline-cloud-for-blender/assets/16008714/ea5f2beb-4ff0-4979-be7b-f4452054d182">
Job submission fails:
<img width="372" alt="image" src="https://github.com/aws-deadline/deadline-cloud-for-blender/assets/16008714/f1b7377f-05db-40df-91b7-7bd967359ff6">
The folder cannot be removed from the file list using the "Remove Selected" button:
<img width="372" alt="image" src="https://github.com/aws-deadline/deadline-cloud-for-blender/assets/16008714/ffaafa9b-f3ab-4544-869d-e29e6baa5682">

### Reproduction Steps

- Create a scene with a fluid simulation
- Bake the scene
- Attempt to submit to Deadline Cloud

### Code Snippet

N/A

**Comment by epmog** [comment]
Sorry for the delay, thanks for the report!

The problematic code appears to be here: https://github.com/aws-deadline/deadline-cloud-for-blender/blob/mainline/src/deadline/blender_submitter/addons/deadline_cloud_blender_submitter/open_deadline_cloud_dialog.py#L60-L65

`find_files` actually returns folders and files - https://github.com/aws-deadline/deadline-cloud-for-blender/blob/mainline/src/deadline/blender_submitter/addons/deadline_cloud_blender_submitter/blender_utils.py#L69-L70

So we should be handling this better.

As a workaround, you should be able to use the `Export Bundle`, modify the `asset_references.yaml` file to remove the reference, and submit the bundle with `deadline bundle submit <path/to/exported/bundle>

**Comment by epmog** [comment]
This should be resolved once https://github.com/aws-deadline/deadline-cloud-for-blender/pull/129 is released
