### ISSUE TITLE
Bug: Submitter on Windows has no X button

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-blender#126]
### Expected Behaviour

When I bring up the submission window, I expect to be able to cancel the submission by hitting the X in the top right of the popup window.

### Current Behaviour

The X in the top right of the popup window is greyed out. I have to either hit "Submit" or "Export Bundle" or completely close out of blender to get the window to go away.

![image](https://github.com/user-attachments/assets/942b5867-8189-4370-a0dd-a5cbbf727e45)

### Reproduction Steps

Install the latest submitter on Blender 4.1. It may happen on other blender versions but I haven't tested.

### Code Snippet

n/a

**Comment by yuanmich2** [comment]
The culprit is this line: https://github.com/aws-deadline/deadline-cloud-for-blender/blob/862c8f930c6fee368e37b9188912a0492f1ba18a/src/deadline/blender_submitter/addons/deadline_cloud_blender_submitter/__init__.py#L83

When I comment out that line, the window appears with an X button. It does indeed stay on top of all windows, as the comments around that line suggest, but I think being able to close the window is more important than being able to let the Submission window go into the background. If it really annoyed a user, they can always minimize it or just close the window and reopen when they are ready to render.

**Comment by mwiebe** [comment]
We found elsewhere that `Qt.Tool` is the flag for this instead of `Qt.WindowStaysOnTopHint`. See https://github.com/aws-deadline/deadline-cloud-for-maya/blob/419a06b73b1b4914561e36e97c95a5e325c61762/src/deadline/maya_submitter/mel_commands.py#L67 for example. If you try switching it, does it stay on top and keep the X button?

**Comment by yuanmich2** [comment]
I think QT.Tool is Option 2, which is right below the line i linked to. That option had it's own issues which is detailed in the comments around it.

In my testing, just commenting out that line I linked gave me the behavior I would have expected where the window stays on top and there is an X button.

**Comment by yuanmich2** [comment]
Interesting note: On Blender 3.6, the submitter has an X button. This seems like just an issue for versions 4+
