### ISSUE TITLE
Bug: Output path is ignored and over written in submitter

### ISSUE THREAD

**Issue by lunacava** [aws-deadline/deadline-cloud-for-blender#136]
### Expected Behaviour

"output path" in submitter is set as the setting render output directory setting in the render tab.

### Current Behaviour

when I submit from Blender, Output path is over written in submitter, ignored what I put in output directory in render tab.
![image (37)](https://github.com/user-attachments/assets/1282dac9-24c0-483a-af27-4d23cf893e1a)

### Reproduction Steps

make a scene,
set render setting, put render output directory in Render tab,
open Deadline Cloud render submitter,
go to Job-specific settings,
output pass is not set as I put in the render tab.
and I need to reset output pass every time submit the job. 

### Code Snippet

*

**Comment by miabatta** [comment]
Hi! Thanks for letting us know about this. I'll be putting up a pull request to fix the bug shortly.

**Comment by miabatta** [comment]
Fixed in the change above. I also noticed you're specifying an output filename in that scene, which the submitter also doesn't support yet- working on adding that next!
