### ISSUE TITLE
Bug: color management information is not captured in Job Attachments

### ISSUE THREAD

**Issue by andymanaws** [aws-deadline/deadline-cloud-for-blender#143]
### Expected Behaviour

It would be great if *somehow* the submitter could determine what color space information ( e.g. configs) are being used in the scene, and then store them as attachments, so that when rendering in SMF color management environments can be duplicated.

Unfortunately there are a number of ways to set this up!
- centralised data referenced by OCIO environment variables
- data dumped into the install location of Blender.

A workaround would be to add something to the queue to pass the OCIO folder , and then assume the config lies within it, and set OCIO - but not sure if this will scale for all use cases ( more complex hierarchical setups, non-centralised locations of data,etc.)

```
{
	"specificationVersion": "environment-2023-09",
	"parameterDefinitions": [
		{
			"name": "ocio_location",
			"type": "PATH",
			"default": "Z:/OCIO/OpenColorIO-Config-ACES-1.2/aces_1.2",
			"dataFlow": "IN",
			"objectType": "DIRECTORY"
		}
	],
	"environment": {
		"name": "ocio_location",
		"script": {
			"actions": {
				"onEnter": {
					"command": "{{Env.File.Enter}}"
				}
			},
			"embeddedFiles": [
				{
					"name": "Enter",
					"type": "TEXT",
					"runnable": true,
					"data": "#!/bin/bash\necho 'openjd_env: OCIO={{Param.ocio_location}}/config.ocio'"
				}
			]
		}
	}
}
```

### Current Behaviour

No OCIO is captured and scenes are loaded with stock Blender color management.

This results is potential render changes.

### Reproduction Steps

1. Setup OCIO

https://opencolorio.readthedocs.io/en/latest/quick_start/for_artists.html

2. Start Blender and start an example scene.

I love Daniel Bystedt's Splash Fox scene:
https://cloud.blender.org/p/gallery/5f4cd4441b96699a87f70fcb

3. Adjust the scene

Within the shading section , adjust the texture nodes to use 'Utility - sRGB - Texture' 

4.Render and compare.

Render locally, render in SMF, compare the differences.
Write out PNG and EXR files.

### Code Snippet

n/a

**Comment by ZainAallii** [comment]
Ran into similar issue with Maya OCIO where OCIO path seems to be translated to some repeated sessions paths. 

```
2024/11/20 11:33:16-08:00 ADAPTOR_OUTPUT: STDOUT: 00:00:06   771MB         | [color_manager] using color manager of type "color_manager_ocio"
2024/11/20 11:33:16-08:00 ADAPTOR_OUTPUT: STDOUT: 00:00:06   771MB ERROR   | [color_manager_ocio] could not read '/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dsessions/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dsession-1b8b0407b1fc4398a3ecd291ab7<redacted>/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21d.env/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dusr/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dautodesk/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dmayaIO2024/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dresources/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dOCIO-configs/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dMaya2022-default/sessions/session-1b8b0407b1fc4398a3ecd291ab7<redacted>/assetroot-3751af5bd81011e6d21dconfig.ocio' OCIO profile.
2024/11/20 11:33:16-08:00 ADAPTOR_OUTPUT: STDOUT: 00:00:06   771MB WARNING | [color_manager] unable to determine rendering color space chromaticities for "ACEScg": using default "linear sRGB" chromaticities
```

Any workarounds for Maya? We can put ocio config where the Maya scene file is so it does not break the path.

**Comment by miabatta** [comment]
Hi! I'm picking this issue up for Blender- thank you Andy for posting the workaround, and Zain for the callout that other submitters behave similarly. I'll be sure to put this on others' radars.
